catalog/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter


from .views import (
    register,
    login_view,
    logout_user,
    profile,
    edit_profile_view,
    confirm_email,
)
from ._views import AccountViewSet


app_name = "accounts"

router = DefaultRouter()
router.register(prefix=r"accounts", viewset=AccountViewSet, basename="accounts")


urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_user, name="logout_user"),
    path("profile/", profile, name="profile"),
    path("edit_profile/", edit_profile_view, name="edit_profile"),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done"),
            template_name="password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change_done",
        PasswordChangeDoneView.as_view(template_name="password_change_done.html"),
        name="password_change_done",
    ),
    path("confirm_email/", confirm_email, name="confirm_email"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/form.html",
            email_template_name="password_reset/email.html",
            success_url="done/",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += router.urls

catalog/catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path("", include("accounts.urls", namespace="accounts")),
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "api/docs/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger-ui",
        ),
        # path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
        path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
        path("api/refresh/", TokenObtainPairView.as_view(), name="token_refresh"),
    ]

catalog/products/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from ._views.views import (
    index,
    about,
    product_details,
    cart_add,
    cart_detail,
    cart_delete,
    checkout,
)
from ._views.product import ProductViewSet
from ._views.category import CaregoryViewSet
from ._views.cart import CartViewSet


app_name = "products"

router = DefaultRouter()
router.register(prefix=r"products", viewset=ProductViewSet)
router.register(prefix=r"categories", viewset=CaregoryViewSet)
router.register(prefix=r"carts", viewset=CartViewSet)


urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("product/<int:product_id>/", product_details, name="product_details"),
    path("cart_add/<int:product_id>/", cart_add, name="cart_add"),
    path("cart_detail/", cart_detail, name="cart_detail"),
    path("cart_delete/<int:product_id>/", cart_delete, name="cart_delete"),
    path("checkout/", checkout, name="checkout"),
]


urlpatterns += router.urls

catalog/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
        upload_to="avatars/", default="avatars/freak.jpg", blank=True
    )

catalog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .serializers import CaptchaFieldSerializer


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    captcha = CaptchaFieldSerializer()

    class Meta:
        model = User
        extra_fields = ["email"]
        fields = ["username", "password1", "password2"]


class ProfileUpdateForm(forms.Form):
    email = forms.EmailField(label="Email:")
    avatar = forms.ImageField(required=False, label="Avatar:")

    def clean_email(self):
        new_email = self.cleaned_data.get("email")
        if User.objects.filter(email=new_email).exists():
            raise ValidationError("User with this Email Already Exists")
        else:
            return new_email

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields["email"].initial = self.user.email


class RegisterFormNoCaptcha(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label="Login:")
    password = forms.CharField(
        widget=forms.PasswordInput(), required=True, label="Password:"
    )

catalog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponseBadRequest
from django.contrib.auth.models import User
from django.conf import settings

from .forms import RegisterForm, ProfileUpdateForm, RegisterFormNoCaptcha
from .models import Profile
from products.models import Cart, Product, CartItem
from utils.email import send_email_confirm


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            request.session["form_data"] = request.POST.dict()
            user = form.save()
            user.is_active = False
            user.save()
            send_email_confirm(request, user, user.email)
            return redirect("accounts:register")
    else:
        form = RegisterForm()
    request.session["last_visited"] = request.path
    return render(request, "register.html", context={"form": form})


def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            session_cart = request.session.get(settings.CART_SESSION_ID)
            if session_cart:
                cart = user.cart
                # cart, _ = Cart.objects.get_or_create(user=user)
                for product_id, amount in session_cart.items():
                    product = Product.objects.get(id=product_id)
                    cart_item, created = CartItem.objects.get_or_create(
                        cart=cart, product=product
                    )
                    if not created:
                        cart_item.amount += amount
                    else:
                        cart_item.amount = amount
                    cart_item.save()
                request.session[settings.CART_SESSION_ID] = {}
            next_url = request.GET.get("next")
            return redirect(next_url or "products:index")
        else:
            return render(
                request, "login.html", context={"error": "Incorrect login or password"}
            )
    return render(request, "login.html")


def logout_user(request):
    logout(request)
    return redirect("products:index")


@login_required
def profile(request):
    profile = request.user.profile
    # profile, _ = Profile.objects.get_or_create(user=request.user)
    return render(request, "profile.html", context={"profile": profile})


@login_required
def edit_profile_view(request):
    user = request.user
    profile = user.profile
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, request.FILES, user=user)
        if form.is_valid():
            new_email = form.cleaned_data.get("email")
            # user.email = new_email
            # user.save()
            if new_email != user.email:
                send_email_confirm(request, user, new_email)

            avatar = form.cleaned_data.get("avatar")
            if avatar:
                profile.avatar = avatar
            profile.save()
            return redirect("accounts:profile")
    else:
        form = ProfileUpdateForm(user=user)
    request.session["last_visited"] = request.path
    return render(
        request, "edit_profile.html", context={"form": form, "profile": profile}
    )


def confirm_email(request):
    previous = request.session.get("last_visited")
    user_id = request.GET.get("user")
    email = request.GET.get("email")
    if not email:
        return HttpResponseBadRequest("Bad Request: No Email")
    if User.objects.filter(email=email).exists():
        return HttpResponseBadRequest("This email is already taken")
    if previous == "/edit_profile/":
        if not user_id:
            return HttpResponseBadRequest("Bad Request: No User")
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return HttpResponseBadRequest("User Not Found")
        user.email = email
        user.save()
    else:
        form_data = request.session.get("form_data")
        form_to_save = RegisterFormNoCaptcha(form_data)
        if form_to_save.is_valid():
            user = form_to_save.save()
            login(request, user)
    return render(request, "confirm_email.html", context={"email": email})

catalog/accounts/templates/confirm_email.html
{% extends 'base.html' %}

{% block content %}
    <h2>Success! Your Email <span class="text-success">{{ email }}</span> has been confirmed!</h2>
    <a href="{% url 'products:index' %}" class="btn btn-success" type="button">Go to Home</a>
{% endblock %}

catalog/accounts/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit Profile</h2>
    {% if profile.avatar %}
        <p>Current Avatar:</p>
        <img src="{{ profile.avatar.url }}" alt="avatar" width="150">
    {% else %}
        <p>No Avatar</p>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Login</h2>
    {% if error %}
        <div class="alert alert danger">
            {{ error }}
        </div>   
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <input class="form-control mb-2" type="text" name="username" placeholder="Username">
        <input class="form-control mb-2" type="password" name="password" placeholder="Password">
        <input type="submit" class="btn btn-primary" value="Login">
    </form>
    <a href="{% url 'accounts:password_reset' %}">Forgot Password</a>
{% endblock %}

catalog/accounts/templates/password_change.html
{% extends 'base.html' %}

{% block content %}
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-warning">Change</button>
    </form>
{% endblock %}

catalog/accounts/templates/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    <div class="alert alert-success">
        Password Changed Successfully
    </div>
    <a href="{% url 'accounts:profile' %}">Go Back to Profile</a>
    
{% endblock %}

catalog/accounts/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>Profile-{{ request.user.username }}</h2>
    {% if messages %}
        {% for message in messages %}
            <p class="text-success">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <ul>
        <img src="{{ profile.avatar.url }}" alt="avatar" width="150">
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>
    <a href="{% url 'accounts:password_change' %}" class="btn btn-primary">Change Password</a>
    <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
    
{% endblock %}

catalog/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        {% if messages %}
            {% for message in messages %}
                <p class="text-success">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <h2>
            Registration Form
        </h2>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" class="btn btn-primary" value="Register">
        </form>
    </div>
{% endblock %}